# https://docs.npmjs.com/cli/configuring-npm/package-json
version: 0.0.0
name: match-up
description: Reliable method to find the root path of your git repo, [p]npm/yarn package or app.
keywords:
- find
- find-up
- path
- glob
- pattern
- match
- config
- walk
- traverse

homepage: https://github.com/danielbayley/match-up#readme
repository: danielbayley/match-up
bugs: https://github.com/danielbayley/match-up/issues

author:
  name: Daniel Bayley
  email: daniel.bayley@me.com
  url: https://danielbayley.dev

funding: https://github.com/danielbayley/match-up?sponsor=1
license: MIT

type: module
exports: &index ./index.js
files: [*index]

engines:
  node: ">=21"
  pnpm: ">=10"
packageManager: pnpm@10.0.0

devDependencies:
  fs-fixture: ^2.7.0
  publint: ^0.3.2
  yaml: ^2.7.0

scripts:
  prepare: yaml --single --json --indent ${TABSIZE:-2} < package.yaml > package.json

  test: node --experimental-test-coverage --test test.js
  watch: pnpm test --watch

  prerelease: git stash --include-untracked --keep-index && pnpm prepare
  release: pnpm version --force --no-git-tag-version
  postrelease: pnpm publish

  prepublishOnly: publint
  postpublish: git stash pop --quiet

  version: >-
    sed -i "" -E "s/(version: *)[0-9]+(\.[0-9]+){2}/\\1$npm_new_version/" package.yaml &&
    git commit --message  $npm_new_version package.yaml &&
    git tag    --annotate $npm_new_version --message v$npm_new_version &&
    git push   --follow-tags
