# https://docs.npmjs.com/cli/configuring-npm/package-json
version: 0.0.0
name: match-up
description: Reliable method to find the root path of your git repo, [p]npm/yarn package or app.
keywords:
- find
- find-up
- path
- glob
- pattern
- match
- config
- walk
- traverse

homepage: https://github.com/danielbayley/match-up#readme
repository: https://github.com/danielbayley/match-up
bugs: https://github.com/danielbayley/match-up/issues

author:
  name: Daniel Bayley
  email: daniel.bayley@me.com
  url: https://danielbayley.dev

license: MIT

type: module
exports: &index ./index.js
files: [*index]

engines:
  node: ">=21"
  pnpm: ">=10"
packageManager: pnpm@10.0.0

devDependencies:
  fs-fixture: ^2.7.0
  yaml: ^2.7.0

scripts:
  prepare: yaml --single --json --indent ${TABSIZE:-2} < package.yaml > package.json
  test: node --experimental-test-coverage --test test.js
  watch: pnpm test --watch
